services:
  consul1:
    image: hashicorp/consul:latest
    hostname: consul1
    container_name: consul1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul-config:/consul/config
    command: agent -server -bootstrap-expect=5 -node=consul1 -ui -client=0.0.0.0 -config-dir=/consul/config
    networks:
      - config-mgt

  consul2:
    image: hashicorp/consul:latest
    hostname: consul2
    container_name: consul2
    volumes:
      - ./consul-config:/consul/config
    command: agent -server -node=consul2 -join=consul1 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - config-mgt

  consul3:
    image: hashicorp/consul:latest
    hostname: consul3
    container_name: consul3
    volumes:
      - ./consul-config:/consul/config
    command: agent -server -node=consul3 -join=consul1 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - config-mgt

  consul4:
    image: hashicorp/consul:latest
    hostname: consul4
    container_name: consul4
    volumes:
      - ./consul-config:/consul/config
    command: agent -server -node=consul4 -join=consul1 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - config-mgt

  consul5:
    image: hashicorp/consul:latest
    hostname: consul5
    container_name: consul5
    volumes:
      - ./consul-config:/consul/config
    command: agent -server -node=consul5 -join=consul1 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - config-mgt

  certificate-authority:
    image: ghcr.io/linuxserver/openssh-server:latest
    hostname: certificate-authority
    container_name: certificate-authority
    restart: on-failure
    volumes:
      - ./ssh-ca:/ssh-ca
      - ./sign.sh:/usr/local/bin/sign.sh
    command: >
      bash -c "
      chmod +x /usr/local/bin/sign.sh &&
      if [ ! -f /ssh-ca/id_rsa ]; then
        ssh-keygen -t rsa -b 4096 -f /ssh-ca/id_rsa -N '' -C 'ca-key';
      fi &&
      tail -f /dev/null"
    networks:
      - config-mgt


  consul-lb:
    image: haproxy:alpine
    container_name: consul-lb
    networks:
      - config-mgt
    ports:
      - "18500:8500"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 3s
      retries: 5

  consul-sync:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./consul_sync.py:/app/consul_sync.py:ro
      - ./ssh-ca/id_rsa.pub:/app/id_rsa.pub:ro  
    command: >
      sh -c "pip install requests && echo '>>> Running consul_sync.py' && python consul_sync.py && tail -f /dev/null"
    networks:
      - config-mgt


networks:
 config-mgt:
    driver: bridge

