# Generated by Django 5.2.1 on 2025-06-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
