# Generated by Django 5.2.1 on 2025-06-11 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_publickey_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
