# Generated by Django 5.2.1 on 2025-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('dev', 'Developer'), ('qa', 'QA'), ('prod', 'Production'), ('admin', 'Admin')], max_length=50),
        ),
    ]
