# Generated by Django 5.2.1 on 2025-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_certificate_revoked_certificate_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
