# Generated by Django 5.2.1 on 2025-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('public_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
